core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.login_view, name='login'),
    path('spotify/login/', views.spotify_login, name='spotify_login'),
    path('spotify/callback/', views.spotify_callback, name='spotify_callback'),
    path('home/', views.homepage, name='home'),
    path('logout/', views.logout_view, name='logout'),
    path('get-top-songs/', views.get_top_songs, name='get-top-songs'),
    path('get-top-artists/', views.get_top_artists, name='get-top-artists'),
    path('get-album-details/<str:album_id>/', views.get_album_details, name='get-album-details'),
    path('test/', views.test, name='test'),
]

spotify/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('accounts/', include('django.contrib.auth.urls'))
]

if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls')),
    ]

core/models.py
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_url = models.URLField(null=True)
    profile_img_1 = models.URLField(null=True)
    profile_img_2 = models.URLField(null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.user.username} Profile'

core/forms.py
from django.forms import Form

core/views.py
import logging
import base64
import datetime
import spotipy
from spotipy.oauth2 import SpotifyOAuth
import pandas as pd

from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import login, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods


from .query import get_users_top_songs, get_users_playlists, get_playlist_data, get_artist_data
from .models import Profile
from .utility import get_spotify_client, convert_str_to_date
from spotify import settings


logger = logging.getLogger(__name__)

logging.basicConfig(
    filename='spotify.log',
    level=logging.DEBUG,
    format='%(asctime)s - %(levelname)s - %(message)s'
)

# AUTHENTICATION VIEWS 
def login_view(request):
    if request.user.is_authenticated:
        return redirect('core:home')
    return render(request, 'core/login.html')

@require_http_methods(['GET'])
def logout_view(request):
    # print("Logging out")
    logout(request)
    return redirect('core:login')

def spotify_login(request):
    sp = spotipy.Spotify(auth_manager=SpotifyOAuth(
        client_id=settings.SPOTIFY_CLIENT_ID, 
        client_secret=settings.SPOTIFY_CLIENT_SECRET, 
        redirect_uri=settings.SPOTIFY_REDIRECT_URI, 
        scope='user-library-read user-top-read'))
    
    # Get the Spotify authorization URL that user will be redirected to
    auth_url = sp.auth_manager.get_authorize_url()
    # Redirect user to Spotify login page
    return redirect(auth_url)


def spotify_callback(request):

    sp = spotipy.Spotify(auth_manager=SpotifyOAuth(
        client_id=settings.SPOTIFY_CLIENT_ID, 
        client_secret=settings.SPOTIFY_CLIENT_SECRET, 
        redirect_uri=settings.SPOTIFY_REDIRECT_URI, 
        scope='user-library-read user-top-read'))
    
    # Get authorization code from callback request parameters
    code = request.GET.get("code")
    if code:
        # Exchange authorization code for access and refresh tokens
        token_info = sp.auth_manager.get_access_token(code)
        access_token = token_info["access_token"]
        refresh_token = token_info["refresh_token"]

        # Create Spotify client with access token
        sp = spotipy.Spotify(auth=access_token)
        # Get current user's profile data
        user_data = sp.current_user()
        logging.debug(f"user_data: {user_data}")
        # Extract user ID and email from profile
        spotify_id = user_data["id"]

        # Create or get existing user in Django database
        user, created = User.objects.get_or_create(username=spotify_id)
        profile, created = Profile.objects.get_or_create(user=user)
        # print(f"user: {user}, created: {created}")
        check_for_profile_changes(profile, user_data)


        # Store Spotify tokens in session for future API calls
        request.session["spotify_access_token"] = access_token
        request.session["spotify_refresh_token"] = refresh_token

        # Log the user into Django
        login(request, user)
        return redirect("core:home")  # Redirect to dashboard after successful login
    else:
        return redirect("core:home")  # Redirect to home if authorization failed
# AUTHENTICATION VIEWS END 

def get_playlist_details():
    # Query for all the songs in the playlist 
    api_query = get_playlist_data('5oUK8DDz1pRG4Tiks11H4p')['items']

    # Extract specific data for songs in playlist
    song_and_artist_list = extract_song_and_artist(api_query)

    # Query for artist data using the Artist ID 
    for entry in song_and_artist_list:
        if entry['Artist_ID']:
            artist_data = get_artist_data(entry['Artist_ID'])
            entry['Genres'] = artist_data['genres']
    
    return song_and_artist_list

# This takes in profile object and user data to see if any changes need to be made
def check_for_profile_changes(profile, user_data):
    modified = False

    profile_url = user_data['external_urls']['spotify']
    profile_img_1 = user_data['images'][0]['url']
    profile_img_2 = user_data['images'][1]['url']

    if any([
        profile.profile_url != profile_url,
        profile.profile_img_1 != profile_img_1,
        profile.profile_img_2 != profile_img_2
    ]):
        modified = True

    if modified:
        profile.profile_url = profile_url
        profile.profile_img_1 = profile_img_1
        profile.profile_img_2 = profile_img_2
        profile.save()

    # print(f"Profile updated: {modified}")

@login_required
def homepage(request):

    return render(request, 'core/index.html')


@require_http_methods(['GET'])
def get_top_songs(request):
    sp = get_spotify_client()

    # Get the time range from the request or use the session value
    time_range_session = request.session.get('song_time_range', None)

    time_range = request.GET.get('song_time_range', time_range_session)

    # Store the time range in the session
    request.session['song_time_range'] = time_range

    top_songs = sp.current_user_top_tracks(limit=12, time_range=time_range)
    top_songs_dicts = []

    # print(f"top_songs: {top_songs['items'][0]}")

    for i in top_songs['items']:
        top_songs_dicts.append({
            'name': i['name'],
            'album': i['album']['name'],
            'album_id': i['album']['id'],
            'artists': [artist['name'] for artist in i['artists']],
            'images': [image['url'] for image in i['album']['images']]
        })

    context = {
        'top_songs_dicts': top_songs_dicts,
        'song_time_range': time_range
    }

    return render(request, 'core/index.html#top_songs_partial', context)

@require_http_methods(['GET'])
def get_top_artists(request):
    sp = get_spotify_client()

    # Get the time range from the request or use the session value
    time_range_session = request.session.get('artist_time_range', None)

    time_range = request.GET.get('artist_time_range', time_range_session)
    # print(f"artist time_range: {time_range}")
    # Store the time range in the session
    request.session['artist_time_range'] = time_range

    top_artists = sp.current_user_top_artists(limit=12, time_range=time_range)
    # print(f"top_artists: {top_artists['items'][0]}")

    top_artists_dicts = []
    for i in top_artists['items']:
        top_artists_dicts.append({
            'name': i['name'],
            'images': [image['url'] for image in i['images']],
            'genres': i['genres']
        })
    
    # logger.debug(f"top_artists_dicts: {top_artists_dicts}")

    context = {
        'top_artists_dicts': top_artists_dicts,
        'artist_time_range': time_range
    }
    
    return render(request, 'core/index.html#top_artists_partial', context)


@require_http_methods(['GET'])
def get_album_details(request, album_id):
    sp = get_spotify_client()
    album_details = sp.album(album_id)
    # print(f"album_details: {album_details}")
    album_details_dict = {
        'name': album_details['name'],
        'id': album_details['id'],
        'type': album_details['album_type'],
        'release_date': convert_str_to_date(album_details['release_date'], '%d/%m/%Y'),
        'total_tracks': album_details['total_tracks'],
        'tracks': album_details['tracks']['items'],
        'images': [image['url'] for image in album_details['images']],
        'artists': [artist['name'] for artist in album_details['artists']],
        'genres': album_details['genres'],
        'link': album_details['external_urls']['spotify']
    }

    context = {
        'album_details': album_details_dict
        }

    return render(request, 'core/partials/album_info_partial.html', context)



def extract_song_and_artist(item):
    song_details_list = []
    for i in item:
        song_details_list.append({'Song_Name': i['track']['name'],
        'Song_ID': i['track']['id'],
        'Album_Name': i['track']['album']['name'],
        'Album_ID': i['track']['album']['id'],
        'Artist_Name': i['track']['artists'][0]['name'],
        'Artist_ID': i['track']['artists'][0]['id']})
    return song_details_list

def extract_genre_from_artist_data(item):
    return item['genres']

def test(request):
    return render(request, 'core/base/test.html')

core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    <script src="https://unpkg.com/htmx.org@2.0.4" integrity="sha384-HGfztofotfshcF7+8n44JQL2oJmowVChPTg48S+jvZoztPfvwD79OC/LTtG6dMp+" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

    <link rel="stylesheet" href="{% static 'core/css/styles.css' %}">
    {% block stylesheet %}{% endblock %}
    
    {% block head %}{% endblock %}
    {% block title %}<title>Spotify App</title>{% endblock %}
</head>

<body>

    {% include 'core/navbar.html' %}
    
{% block content %}
{% endblock %}


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
{% block script %}
{% endblock %}
</body>
</html>

core/templates/core/index.html
{% extends 'core/base/base.html' %} 
{% load static %} 
{% load partials %}

{% block stylesheet %}
<link rel="stylesheet" href="{% static 'core/css/index.css' %}">
{% endblock %}

{% block content %}



<div class="container">
  <div class="header">
    <h1>Spotify Playlist Analysis</h1>
    <p>Discover insights about your favorite tracks</p>
  </div>


  <!-- Top song section  -->
  <section class="mb-3" id="topSongs" 
          hx-get="{% url 'core:get-top-songs' %}" 
          hx-target="#top-songs-container" 
          hx-swap="innerHTML"
          hx-trigger="revealed">

    <div class="row">
      <div class="col-12">


        <div class="card" id="top-songs-container">
          {% partialdef top_songs_partial inline %}
          <div class="card-body">
            
            <div class="d-flex align-items-center justify-content-between mb-3">
              
              <h5 class="card-title">Your Top Songs</h5>

                <div class="btn-group" role="group" aria-label="Time Range">
                  <button type="button" 
                          class="btn btn-outline-light {% if not song_time_range or song_time_range == 'short_term' %}active{% endif %}"
                          hx-get="{% url 'core:get-top-songs' %}?song_time_range=short_term" 
                          hx-target="#top-songs-container" 
                          hx-swap="innerHTML"
                          >4 weeks</button>

                  <button type="button" 
                          class="btn btn-outline-light {% if song_time_range == 'medium_term' %}active{% endif %}"
                          hx-get="{% url 'core:get-top-songs' %}?song_time_range=medium_term" 
                          hx-target="#top-songs-container" 
                          hx-swap="innerHTML"
                          >6 months</button>
                  
                  <button type="button" 
                          class="btn btn-outline-light {% if song_time_range == 'long_term' %}active{% endif %}"
                          hx-get="{% url 'core:get-top-songs' %}?song_time_range=long_term" 
                          hx-target="#top-songs-container" 
                          hx-swap="innerHTML"
                          >1 year</button>
                </div>
              </div>
            </div>

            <div class="row">
              
                {% for song in top_songs_dicts %}
                <div class="col-md-2 col-6 mb-3">
                  
                  <div class="card song-card h-100">
                    <div class="card-body d-flex flex-column">
                      <div class="text-truncate">
                        <h5 class="card-title mb-2">{{ song.name|truncatechars:20 }}</h5>
                      </div>
                      <img src="{{ song.images.0 }}" alt="Album Cover" class="img-fluid mb-2">

                      
                      <div class="mt-auto text-truncate">
                        <i class="fa-regular fa-user" style="color: #1DB954;"></i>
                        {% for artist in song.artists %}
                          <span class="text-white">
                            {{ artist }}{% if not forloop.last %}, {% endif %}
                          </span>
                        {% endfor %}
                      </div>

                      <div class="text-truncate">
                        <i class="fa-solid fa-compact-disc" style="color: #1DB954;"></i>
                        <span class="text-white"
                              data-bs-toggle="modal" 
                              data-bs-target="#detailModal" 
                              hx-get="{% url 'core:get-album-details' song.album_id %}" 
                              hx-target="#modal-container" 
                              hx-trigger="click"
                              hx-swap="innerHTML">
                            {{ song.album }}
                        </span>
                      </div>
                      

                    </div>
                  </div>
                  
                </div>
                {% endfor %}
              
            </div>
            {% endpartialdef %}
          </div>
        </div>
        <!-- TOP SONGS COL END  -->
      </div>
      <!-- TOP SONGS ROW END  -->
  </section>
  <!-- TOP SONGS SECTION END  -->


  <!-- Top Artist Section  -->
  <section class="mb-3" id="topArtists"
          hx-get="{% url 'core:get-top-artists' %}"
          hx-target="#top-artists-container"
          hx-swap="innerHTML"
          hx-trigger="revealed">

    <div class="row">
      <div class="col-12">
        <div class="card" id="top-artists-container">
          {% partialdef top_artists_partial inline %}
          <div class="card-body">

            <div class="d-flex align-items-center justify-content-between mb-3">

              <h5 class="card-title">Your Top Artists</h5>

              <div class="btn-group" role="group" aria-label="Time Range">
                <button type="button" 
                        class="btn btn-outline-light {% if not artist_time_range or artist_time_range == 'short_term' %}active{% endif %}"
                        hx-get="{% url 'core:get-top-artists' %}?artist_time_range=short_term" 
                        hx-target="#top-artists-container" 
                        hx-swap="innerHTML"
                        >4 weeks</button>

                <button type="button" 
                        class="btn btn-outline-light {% if artist_time_range == 'medium_term' %}active{% endif %}"
                        hx-get="{% url 'core:get-top-artists' %}?artist_time_range=medium_term" 
                        hx-target="#top-artists-container" 
                        hx-swap="innerHTML"
                        >6 months</button>
                
                <button type="button" 
                        class="btn btn-outline-light {% if artist_time_range == 'long_term' %}active{% endif %}"
                        hx-get="{% url 'core:get-top-artists' %}?artist_time_range=long_term" 
                        hx-target="#top-artists-container" 
                        hx-swap="innerHTML"
                        >1 year</button>
                </div>
              </div>
            </div>
            

            <div class="row">
              
              {% for artist in top_artists_dicts %}
              <div class="col-md-2 col-6 mb-3">
                <div class="card artist-card h-100">
                  <div class="card-body d-flex flex-column justify-content-between">

                    <h5 class="card-title mb-2">{{ artist.name|truncatechars:20 }}</h5>

                    <img src="{{ artist.images.1 }}" alt="Artist Image" class="img-fluid mb-2">

                    <div class="mt-auto text-truncate">
                      {% for genre in artist.genres %}
                        <small class="text-white">
                          {{ genre }}{% if not forloop.last %}, {% endif %}
                        </small>
                      {% endfor %}
                    </div>

                  </div>
                </div>
              </div>
              {% endfor %}
            </div>
            {% endpartialdef %}
          </div>


        </div>
      </div>
    </div>
  </section>
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#detailModal">
  Launch demo modal
</button>
</div>

<!-- Basic Modal -->
<div class="modal fade" id="detailModal" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-body">
        <!-- Modal content goes here -->
        <button type="button" class="btn-close btn-close-white float-end" data-bs-dismiss="modal" aria-label="Close"></button>
        <div id="modal-container">
          
        <!-- Album name -->
        <!-- Album picture  -->
        <!-- Release Date  -->
        <!-- Tracks  -->
        <!-- Artists  -->
        <!-- Genres  -->
        <!-- Link to spotify  -->
        </div>

        

      </div>
    </div>
  </div>
</div>

{% endblock %}

core/templates/core/login.html
{% extends 'core/base/base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <div class="row justify-content-center align-items-center min-vh-100">
        <div class="col-md-6">
            <div class="card bg-dark text-white">
                <div class="card-body text-center">
                    <h2 class="mb-4">Welcome to Spotify Analytics</h2>
                    <p class="mb-4">Analyze your Spotify playlists and discover insights about your music</p>
                    <a href="{% url 'core:spotify_login' %}" class="btn btn-success btn-lg">
                        <i class="fab fa-spotify me-2"></i>Login with Spotify
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

core/templates/core/navbar.html
<nav class="navbar">
    <div class="navbar-container">
        <a href="#" class="navbar-brand">Spotify Analytics</a>
        <div class="navbar-right">
            {% if user.is_authenticated %}
                <div class="dropdown">
                    <img src="{{ profile.profile_img_2 }}" alt="Profile Image" class="profile-image" data-bs-toggle="dropdown" aria-expanded="false" />
                    <ul class="dropdown-menu">
                      <li><a class="dropdown-item" href="#">Profile</a></li>
                      <li><a class="dropdown-item" href="#">Dashboard</a></li>
                      <li><a class="dropdown-item" href="#">Settings</a></li>
                      <li><a class="dropdown-item" href="#">Notifications</a></li>
                      <li><a class="dropdown-item" href="#">Charts</a></li>
                      <li><a class="dropdown-item" href="{% url 'core:logout' %}">Log Out</a></li>
                    </ul>
                  </div>
            {% else %}
                <a href="{% url 'core:spotify_login' %}" class="login-button">Login</a>
            {% endif %}
        </div>
    </div>
</nav>